######################################################################
# Automatically generated by qmake (2.01a) Mon May 4 17:53:42 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += widget.h
SOURCES += main.cpp widget.cpp
